-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 19:31:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MathSportsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MathSportsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MathSportsDB` DEFAULT CHARACTER SET utf8 ;
USE `MathSportsDB` ;

-- -----------------------------------------------------
-- Table `MathSportsDB`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `First` VARCHAR(45) NULL,
  `Last` VARCHAR(45) NULL,
  `ClassID` VARCHAR(45) NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Teacher` (
  `TeacherID` INT NOT NULL AUTO_INCREMENT,
  `First` VARCHAR(45) NULL,
  `Last` VARCHAR(45) NULL,
  `ClassID` VARCHAR(45) NULL,
  PRIMARY KEY (`TeacherID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Questions` (
  `QuestionID` INT NOT NULL AUTO_INCREMENT,
  `QuestionType` INT NOT NULL,
  PRIMARY KEY (`QuestionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`Addition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Addition` (
  `FirstNum` INT NOT NULL,
  `SecNum` INT NOT NULL,
  `Ans` INT NOT NULL,
  `QuestionID` INT NOT NULL,
  PRIMARY KEY (`QuestionID`),
  CONSTRAINT `QuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Questions` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`Subtraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Subtraction` (
  `QuestionID` INT NOT NULL AUTO_INCREMENT,
  `FirstNum` INT NOT NULL,
  `SecNum` INT NOT NULL,
  `Ans` INT NOT NULL,
  PRIMARY KEY (`QuestionID`),
  CONSTRAINT `QuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Questions` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`PlaceValue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`PlaceValue` (
  `QuestionID` INT NOT NULL AUTO_INCREMENT,
  `FirstDigit` INT NOT NULL,
  `SecondDigit` INT NOT NULL,
  `ThirdDigit` INT NOT NULL,
  PRIMARY KEY (`QuestionID`),
  CONSTRAINT `QuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Questions` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Tests` (
  `TestID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`TestID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`HW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`HW` (
  `HWID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HWID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`TestHasQuestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`TestHasQuestions` (
  `QuestionID` INT NOT NULL,
  `TestID` INT NOT NULL,
  INDEX `QuestionID_idx` (`QuestionID` ASC),
  INDEX `TestID_idx` (`TestID` ASC),
  CONSTRAINT `QuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Questions` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TestID`
    FOREIGN KEY (`TestID`)
    REFERENCES `mydb`.`Tests` (`TestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`HWHasQuestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`HWHasQuestions` (
  `QuestionID` INT NOT NULL,
  `HWID` INT NOT NULL,
  INDEX `HWID_idx` (`HWID` ASC),
  INDEX `QuestionID_idx` (`QuestionID` ASC),
  CONSTRAINT `HWID`
    FOREIGN KEY (`HWID`)
    REFERENCES `mydb`.`HW` (`HWID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `QuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Questions` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`Class` (
  `ClassID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ClassID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`ClassHasStudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`ClassHasStudents` (
  `StudentID` INT NOT NULL,
  `ClassID` INT NOT NULL,
  INDEX `ClassID_idx` (`ClassID` ASC),
  INDEX `StudentID_idx` (`StudentID` ASC),
  CONSTRAINT `ClassID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mydb`.`Class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudentID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`ClassHasTeacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`ClassHasTeacher` (
  `ClassId` INT NOT NULL,
  `TeacherID` INT NOT NULL,
  INDEX `ClassID_idx` (`ClassId` ASC),
  INDEX `TeacherID_idx` (`TeacherID` ASC),
  CONSTRAINT `ClassID`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb`.`Class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TeacherID`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `mydb`.`Teacher` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`ClassHasHW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`ClassHasHW` (
  `HWID` INT NOT NULL,
  `ClassID` INT NOT NULL,
  INDEX `HWID_idx` (`HWID` ASC),
  INDEX `ClassID_idx` (`ClassID` ASC),
  CONSTRAINT `ClassID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mydb`.`Class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HWID`
    FOREIGN KEY (`HWID`)
    REFERENCES `mydb`.`HW` (`HWID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MathSportsDB`.`ClassHasTests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MathSportsDB`.`ClassHasTests` (
  `ClassID` INT NOT NULL,
  `TestID` INT NOT NULL,
  INDEX `TestID_idx` (`TestID` ASC),
  INDEX `ClassID_idx` (`ClassID` ASC),
  CONSTRAINT `TestID`
    FOREIGN KEY (`TestID`)
    REFERENCES `mydb`.`Tests` (`TestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mydb`.`Class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
